os: linux
dist: xenial
language: python

python:
  - "3.7"

services:
  - docker

jobs:
  include:
    - name: "Python 3.7 on Linux Ubuntu"
      python: 3.7
      env: DJANGO_VERSION=3.0.5 TEST_DB_ENGINE=psql DATABASE_URL=postgres://travis:travis@localhost/mcetest

before_install:
  - python -m pip install --upgrade pip
  - if [[ $TEST_DB_ENGINE == psql ]]; then
       docker run -d -p 5432:5432 -e POSTGRES_DB=travis -e POSTGRES_USER=travis -e POSTGRES_PASSWORD=travis -e POSTGRES_DB=mcetest postgres:12-alpine;
       pip install psycopg2-binary;
    fi

install:
  - pip install -e .[tests]
  - pip install coveralls

script:
  - black -S -t py37 --exclude \.migrations --check mce_django_app
  - pytest

after_script:
  - coveralls

