language: python

sudo: true

dist: xenial

python:
 - "3.7"

services:
 - redis-server
 - postgresql

addons:
  postgresql: "12"

env:
 - DATABASE_URL="postgres://travis:travis@localhost/mce_test"
 - DJANGO_SETTINGS_MODULE=tests.app_test.settings
 - MCE_LOG_LEVEL=ERROR

install:
 - pip install -e .[tests]
 - pip install coveralls

before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"
  - psql -c 'create database mce_test;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE mce TO travis';

script:
  - black -S -t py37 --exclude \.migrations --check mce_django_app
  - pytest

after_script:
  - coveralls

