os: linux
dist: xenial
language: python

python:
  - "3.7"

services:
  - docker

jobs:
  include:
    - name: "Python 3.7 on Linux Ubuntu - SQLITE"
      python: 3.7
      env: DJANGO_VERSION=3.0.5 TEST_DB_ENGINE=sqlite DATABASE_URL=sqlite:////tmp/test-sqlite.db CACHE_URL=redis://127.0.0.1:6379/0
    - name: "Python 3.7 on Linux Ubuntu - PSQL"
      python: 3.7
      env: DJANGO_VERSION=3.0.5 TEST_DB_ENGINE=psql DATABASE_URL=postgres://travis:travis@localhost/mcetest CACHE_URL=redis://127.0.0.1:6379/0
    #- name: "Python 3.7 on Linux Ubuntu - MYSQL"
    #  python: 3.7
    #  env: DJANGO_VERSION=3.0.5 TEST_DB_ENGINE=mysql DATABASE_URL=mysql://travis:travis@localhost/mcetest CACHE_URL=redis://127.0.0.1:6379/0
  
before_install:
  - pip install -U pip

  - if [[ "$TEST_DB_ENGINE" == "psql" ]]; then
       docker run -d -p 5432:5432 -e POSTGRES_DB=travis -e POSTGRES_USER=travis -e POSTGRES_PASSWORD=travis -e POSTGRES_DB=mcetest postgres:12-alpine;
       pip install psycopg2-binary;
    fi

install:
  - pip install -e .[tests,ci]
  - pip freeze

script:
  - ./manage.py test -- -m 'not mce_known_bug'
  - bandit -r --ini .bandit mce_django_app -vv

after_success:
  - coveralls
  - codecov

