# Generated by Django 3.0.5 on 2020-05-13 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mce_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectgcp',
            options={'verbose_name': 'GCP Project', 'verbose_name_plural': 'GCP Projects'},
        ),
        migrations.AlterModelOptions(
            name='resourceaws',
            options={'verbose_name': 'AWS Resource', 'verbose_name_plural': 'AWS Resources'},
        ),
        migrations.AlterModelOptions(
            name='resourcegcp',
            options={'verbose_name': 'GCP Project', 'verbose_name_plural': 'GCP Projects'},
        ),
        migrations.RemoveField(
            model_name='projectgcp',
            name='password',
        ),
        migrations.RemoveField(
            model_name='projectgcp',
            name='username',
        ),
        migrations.AddField(
            model_name='projectgcp',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mce_django_app_projectgcp_related', related_query_name='mce_django_app_projectgcps', to='mce_django_app.Company'),
        ),
        migrations.AddField(
            model_name='projectgcp',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectgcp',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mce_django_app.Provider'),
        ),
        migrations.AddField(
            model_name='resourceaws',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mce_django_app.Region'),
        ),
        migrations.AlterField(
            model_name='projectgcp',
            name='project_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Project ID'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
