# Generated by Django 3.0.5 on 2020-04-20 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mce_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='genericaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mce_django_app.Company'),
        ),
        migrations.AlterField(
            model_name='subscriptionazure',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mce_django_app_subscriptionazure_related', related_query_name='mce_django_app_subscriptionazures', to='mce_django_app.GenericAccount'),
        ),
    ]
