# Generated by Django 3.0.5 on 2020-04-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mce_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetype',
            name='exclude_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='GenericAccount',
        ),
    ]
