# Generated by Django 3.0.5 on 2020-05-08 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import jsonfield.fields
import mce_django_app.models.common


class Migration(migrations.Migration):

    dependencies = [
        ('mce_django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=300, overwrite=True, populate_from=['user__username'], primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
            bases=(mce_django_app.models.common.BaseModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='zone',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='region',
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='resourceeventchange',
            options={'ordering': ['-created', 'object_id']},
        ),
        migrations.RemoveField(
            model_name='company',
            name='zones',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='categories',
        ),
        migrations.AddField(
            model_name='resourceazure',
            name='managed_by',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='resourceazure',
            name='plan',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from=['name']),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('provider', 'name'), name='provider_name_uniq'),
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
