# Generated by Django 3.0.5 on 2020-05-13 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mce_django_app', '0002_auto_20200513_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcenter',
            name='provider',
            field=models.ForeignKey(default='vmware', on_delete=django.db.models.deletion.PROTECT, to='mce_django_app.Provider'),
        ),
        migrations.AlterField(
            model_name='projectgcp',
            name='provider',
            field=models.ForeignKey(default='gcp', on_delete=django.db.models.deletion.PROTECT, to='mce_django_app.Provider'),
        ),
        migrations.AlterField(
            model_name='subscriptionaws',
            name='provider',
            field=models.ForeignKey(default='aws', on_delete=django.db.models.deletion.PROTECT, to='mce_django_app.Provider'),
        ),
        migrations.AlterField(
            model_name='subscriptionazure',
            name='provider',
            field=models.ForeignKey(default='azure', on_delete=django.db.models.deletion.PROTECT, to='mce_django_app.Provider'),
        ),
    ]
