# Generated by Django 3.0.5 on 2020-05-16 13:26

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import mce_django_app.models.common


class Migration(migrations.Migration):

    dependencies = [
        ('mce_django_app', '0002_delete_taskresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='inventory_mode',
        ),
        migrations.RemoveField(
            model_name='company',
            name='providers',
        ),
        migrations.RemoveField(
            model_name='company',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='company',
            name='resource_types',
        ),
        migrations.AlterField(
            model_name='region',
            name='display_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='SyncSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from=['name'], unique=True)),
                ('is_global', models.BooleanField(default=False)),
                ('inventory_mode', models.CharField(choices=[('pull', 'Pull'), ('push', 'Push'), ('event', 'Event'), ('queue', 'Queue')], default='pull', max_length=20)),
                ('delete_mode', models.CharField(choices=[('disable', 'Disable'), ('mark', 'Mark'), ('delete', 'Delete')], default='disable', max_length=20)),
                ('exclude_providers', models.ManyToManyField(related_name='syncsettings_exclude', to='mce_django_app.Provider')),
                ('exclude_regions', models.ManyToManyField(related_name='syncsettings_exclude', to='mce_django_app.Region')),
                ('exclude_resource_types', models.ManyToManyField(related_name='syncsettings_exclude', to='mce_django_app.ResourceType')),
                ('include_providers', models.ManyToManyField(related_name='syncsettings_include', to='mce_django_app.Provider')),
                ('include_regions', models.ManyToManyField(related_name='syncsettings_include', to='mce_django_app.Region')),
                ('include_resource_types', models.ManyToManyField(related_name='syncsettings_include', to='mce_django_app.ResourceType')),
            ],
            options={
                'verbose_name': 'Synchronization Settings',
                'verbose_name_plural': 'Synchronization SyncSettings',
                'ordering': ['name'],
            },
            bases=(mce_django_app.models.common.BaseModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='company',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mce_django_app.SyncSettings'),
        ),
        migrations.AddField(
            model_name='projectgcp',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mce_django_app.SyncSettings'),
        ),
        migrations.AddField(
            model_name='subscriptionaws',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mce_django_app.SyncSettings'),
        ),
        migrations.AddField(
            model_name='subscriptionazure',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mce_django_app.SyncSettings'),
        ),
        migrations.AddField(
            model_name='vcenter',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mce_django_app.SyncSettings'),
        ),
    ]
